version: "3"

services:  
  api-ura-toyota-production:
    image: $REGISTRY
    logging:
      driver: "json-file"
      options:
         max-file: 1
         max-size: 10m    
    hostname: apiuratoyotaproduction
    ports:
     - "7550:80" 
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    deploy:
      replicas: 1
      mode: replicated